### ISSUE TITLE
Milestone 1 changelog: 23/5/2022 - 30/5/2022

### ISSUE THREAD

**Issue by xmlew** [xmlew/UniMod#3]
Backend:
Creation of MongoDB database using MongoDB compass with University Module Dat
Registration function and module subscription level functions developed and integrated with database
Backend API using Node.js, available in server folder.

Frontend:
Login page development using HTML and CSS
Figma files designed
UI design flow developed

**Comment by xmlew** [comment]
31/5/2022 - 15/6/2022 Proposed Changelog:
Backend and Frontend integration with login system
Obtaining of NUS Module data via survey and applying new functions
Module management to be used in conjunction with nusmods API
Fully functional frontend pages

**Comment by aerodromic** [comment]
#6 #7 Completed Milestone 1!
